language: node_js

node_js:
  - 8
  - 10

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn ci

notifications:
  email: false

cache:
  yarn: true
  directories:
    - 'node_modules'
